### ISSUE TITLE
`motion2` isn't working with `substitute.range`

### ISSUE THREAD

**Issue by lmburns** [gbprod/substitute.nvim#58] opened 2023-02-23 18:09 UTC
I am unable to type the replacement text with the following mappings/commands.
I have tried the following mappings, trying both `silent=true|false`, and `noremap=true|false`:

```lua
-- Using `.operator()`
map(
    "n",
    "s;",
    "<Cmd>lua require('substitute.range').operator({motion1 = 'iw', motion2 = 'ie'})<CR>",
    {silent = false, noremap = true}
)

-- Or use `.word()`
map(
    "n",
    "s;",
    "<Cmd>lua require('substitute.range').word({motion2 = 'ie'})<CR>",
    {silent = false, noremap = true}
)

-- Or using a Lua function
map(
    "n",
    "s;",
    function()
        return require("substitute.range").word({motion2 = "ie"})
    end,
    {silent = false, noremap = true}
)
```

I have also tried to run these commands with command mode, and I am still unable to type in the replacement text. (i.e., `:lua require("substitute.range").word({motion2 = "ie"})`).

I am able to **successfully** provide the replacement text after I manually enter the second motion if I use the following mappings:

```lua
map(
    "n",
    "s;",
    "<Cmd>lua require('substitute.range').operator({motion1 = 'iw'})<CR>",
    {silent = false, noremap = true}
)

map(
    "n",
    "s;",
    "<Cmd>lua require('substitute.range').word()<CR>",
    {silent = false, noremap = true}
)
```

### Configuration

```lua
require('substitute').setup({
    yank_substituted_text = false,
    range = {
        prefix = "s",
        suffix = "",
        prompt_current_text = false,
        group_substituted_text = true,
        complete_word = true,
        confirm = false,
        register = nil
    }
})
```

**Comment by gbprod** [comment] 2023-02-24 06:43
I think I see where it comes from, it could be a caused by #55 fix

**Comment by gbprod** [comment] 2023-02-27 08:21
Should be fixed now, can you confirm ?

**Closed** 2023-02-27 08:20 UTC
Labels: bug
